name: course_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  user_repository:
    path: ../user_repository
    
  # # equatable: ^2.0.5
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  uuid: ^4.4.2
  firebase_storage: ^11.7.7
  # # firebase_storage: ^11.6.0
  # rxdart: ^0.27.7
  # # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true