// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFExvbk_Aq-bokyMdoHW3y-1wsqkjac7c',
    appId: '1:136625140116:web:1cc1ae2b1a9e8d4c7a1f81',
    messagingSenderId: '136625140116',
    projectId: 'estu-attendance-app',
    authDomain: 'estu-attendance-app.firebaseapp.com',
    storageBucket: 'estu-attendance-app.appspot.com',
    measurementId: 'G-N1DP9M593P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFtfHyfd4l6BCUM5K9al9fxLd7x_TUG8',
    appId: '1:136625140116:android:ddd7a2395c748f9b7a1f81',
    messagingSenderId: '136625140116',
    projectId: 'estu-attendance-app',
    storageBucket: 'estu-attendance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnCjD6I_Dg8FXiJSmbeqnyOJJhmvjuFA',
    appId: '1:136625140116:ios:b6e8627d55d47baf7a1f81',
    messagingSenderId: '136625140116',
    projectId: 'estu-attendance-app',
    storageBucket: 'estu-attendance-app.appspot.com',
    iosBundleId: 'com.example.estuAttendanceApp',
  );
}
